springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
  cache:
    disabled: true
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
  datasource-h2:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:~/test
      username: sa
      password:
  datasource-oracle:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: root12

logging:
  level:
    root: INFO
    '[kr.hrd]' : TRACE